### ISSUE TITLE
Tests fail for phone numbers

### ISSUE THREAD

**Issue by sanojb** [FamilySearch/gedcom5-conversion#10]
I tried to build the converter and since neither I nor Maven could find org.folg.gedcom, I compiled FamilySearch/Gedcom myself and used the snippet

```
<dependency>
      <groupId>org.folg.gedcom</groupId>
      <artifactId>gedcom</artifactId>
      <version>${gedcom.version}</version>
	  <scope>system</scope>
      <systemPath>${project.basedir}/libs/gedcom-1.2-SNAPSHOT.jar</systemPath>
</dependency>
```

But now I get the failing tests below. Am I using the wrong artifact? And which version is correct? The assumptions in the test cases or the parsed version?

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@6f75e721
Tests run: 54, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 8.625 sec <<< FAILURE!
testToOrganization1(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest)  Time elapsed: 0.055 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected phone: data:/,Phone%3A%20866-000-0000
        at org.testng.Assert.fail(Assert.java:89)
        at org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest.testToOrganization1(SourceDescriptionMapperOrganizationTest.java:98)

testToOrganization3(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected phone: data:/,Phone%3A%20(731)%20642-8655,%20Extension%20%23109
        at org.testng.Assert.fail(Assert.java:89)
        at org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest.testToOrganization3(SourceDescriptionMapperOrganizationTest.java:196)

testToOrganization4(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected phone: data:/,Fax%3A%20479-444-1777
        at org.testng.Assert.fail(Assert.java:89)
        at org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest.testToOrganization4(SourceDescriptionMapperOrganizationTest.java:258)

testToOrganization5(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: expected:<tel:+1%20573.204-2331> but was:<tel:/+1%20573.204-2331>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:171)
        at org.testng.Assert.assertEquals(Assert.java:181)
        at org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest.testToOrganization5(SourceDescriptionMapperOrganizationTest.java:298)

testToOrganization7(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected phone: data:/,Phone%3A%20801-533-3535%20%3C%3E
        at org.testng.Assert.fail(Assert.java:89)
        at org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest.testToOrganization7(SourceDescriptionMapperOrganizationTest.java:389)

testToContributor1(org.gedcomx.conversion.gedcom.dq55.SubmitterMapperTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[data:,Phone%3A%20935-555-1212, data:,Fax%3A%20935-555-0101]> but was:<[data:/,Phone%3A%20935-555-1212, data:/,Fax%3A%20935-555-0101]>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:171)
        at org.testng.Assert.assertEquals(Assert.java:181)
        at org.gedcomx.conversion.gedcom.dq55.SubmitterMapperTest.testToContributor1(SubmitterMapperTest.java:69)


Results :

Failed tests:   testToOrganization1(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest): Unexpected phone: data:/,Phone%3A%20866-000-0000
  testToOrganization3(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest): Unexpected phone: data:/,Phone%3A%20(731)%20642-8655,%20Extension%20%23109
  testToOrganization4(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest): Unexpected phone: data:/,Fax%3A%20479-444-1777
  testToOrganization5(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest): expected:<tel:+1%20573.204-2331> but was:<tel:/+1%20573.204-2331>
  testToOrganization7(org.gedcomx.conversion.gedcom.dq55.SourceDescriptionMapperOrganizationTest): Unexpected phone: data:/,Phone%3A%20801-533-3535%20%3C%3E
  testToContributor1(org.gedcomx.conversion.gedcom.dq55.SubmitterMapperTest): expected:<[data:,Phone%3A%20935-555-1212, data:,Fax%3A%20935-555-0101]> but was:<[data:/,Phone%3A%20935-555-1212, data:/,Fax%3A%20935-555-0101]>


Tests run: 54, Failures: 6, Errors: 0, Skipped: 0
```

**Comment by stoicflame** [comment]
Thanks for the report. We'll take a look.
