### ISSUE TITLE
Problem with coding

### ISSUE THREAD

**Issue by obtim** [FamilySearch/gedcom5-conversion#11]
09:46:32.281 ERROR - SAXException: Unrecognized encoding in gedcom file: ISO-885
9-5 @ 0
Exception in thread "main" org.xml.sax.SAXParseException; systemId: file:/C:/tem
p/New.ged; lineNumber: 0; SAXException: Unrecognized encoding in gedcom file: IS
O-8859-5
        at org.gedml.GedcomParser.parse(GedcomParser.java:369)
        at org.folg.gedcom.parser.ModelParser.parseGedcom(ModelParser.java:1552)

        at org.gedcomx.tools.Gedcom2Gedcomx.convert55File(Gedcom2Gedcomx.java:18
5)
        at org.gedcomx.tools.Gedcom2Gedcomx.doMain(Gedcom2Gedcomx.java:156)
        at org.gedcomx.tools.Gedcom2Gedcomx.main(Gedcom2Gedcomx.java:222)

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Finally fixed at 477bc6f16a02f214a2fbb9db5e05e7b5a40b9701.
