### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by CisSasGot** [FamilySearch/gedcom5-conversion#13]
root@CISSASGOT-PC:/mnt/c/WWW/gedcom5-conversion/tmp# java -jar gedcom-converter.jar -i my.ged -o my.gedx
Exception in thread "main" java.lang.NullPointerException
        at org.gedcomx.conversion.gedcom.dq55.SubmitterMapper.toContributor(SubmitterMapper.java:34)
        at org.gedcomx.conversion.gedcom.dq55.GedcomMapper.toGedcomx(GedcomMapper.java:42)
        at org.gedcomx.conversion.gedcom.dq55.GedcomMapper.toGedcomx(GedcomMapper.java:33)
        at org.gedcomx.tools.Gedcom2Gedcomx.convert55File(Gedcom2Gedcomx.java:202)
        at org.gedcomx.tools.Gedcom2Gedcomx.doMain(Gedcom2Gedcomx.java:156)
        at org.gedcomx.tools.Gedcom2Gedcomx.main(Gedcom2Gedcomx.java:222)
root@CISSASGOT-PC:/mnt/c/WWW/gedcom5-conversion/tmp#

**Comment by stoicflame** [comment]
Fixed in 1.4.0, building now:

https://gedcom.ci.cloudbees.com/job/gedcom-to-gedcomx-converter/38/

Thanks for the report.
