### ISSUE TITLE
fasterxml NoSuchMethodError 

### ISSUE THREAD

**Issue by bremet15** [FamilySearch/gedcom5-conversion#21]
`>java -jar target/gedcom5-conversion-1.14.0-SNAPSHOT-full.jar -i "C:\temp\xxxx.ged" -o c:/temp/my.gedx`

C:\Temp>java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.JsonGenerator.writeStartObject(java.lang.Object)'
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:162)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2795)
        at org.gedcomx.fileformat.JacksonJsonSerialization.serialize(JacksonJsonSerialization.java:64)
        at org.gedcomx.fileformat.GedcomxOutputStream.addResource(GedcomxOutputStream.java:135)
        at org.gedcomx.fileformat.GedcomxOutputStream.addResource(GedcomxOutputStream.java:106)
        at org.gedcomx.tools.Gedcom2Gedcomx.convert55File(Gedcom2Gedcomx.java:205)
        at org.gedcomx.tools.Gedcom2Gedcomx.doMain(Gedcom2Gedcomx.java:157)
        at org.gedcomx.tools.Gedcom2Gedcomx.main(Gedcom2Gedcomx.java:215)
```

I updated to pom to use

```
 <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-smile</artifactId>
      <version>2.10.2</version>
```

It worked..

**Comment by BezBlazen** [comment]
I had the same problem. This advice helped me.
